logging:
  level:
    org:
      springframework:
        security: trace
spring:
  security:
    oauth2:
      client:
        registration:
          my-oauth-demo:
            provider: github-oauth
            client-name: my-oauth-demo
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-id: Ov23ct5Ipo4Ga0sbHNHG
            client-secret: 1da0426c3b173d8180f9f2bc686b16cecf6688d4
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github-oauth:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-info-authentication-method: header
            user-name-attribute: name
server:
  port: 80