name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: build a Docker image
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker image build . --file Dockerfile --tag spring-security-oauth2-login:$(date +%s)
